; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{1729CFC1-2935-4EC1-8589-D903175D07B1}
AppName=CGDI
AppVersion=0.0.1
;AppVerName=CGDI 0.0.1
DefaultDirName={pf}\CGDI
DisableProgramGroupPage=yes
OutputBaseFilename=setup
Compression=lzma
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\g_hidalgo\Documents\Calculadora-de-incidentes\CGDI-win32-x64\CGDI.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\g_hidalgo\Documents\Calculadora-de-incidentes\CGDI-win32-x64\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{commonprograms}\CGDI"; Filename: "{app}\CGDI.exe"
Name: "{commondesktop}\CGDI"; Filename: "{app}\CGDI.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\CGDI.exe"; Description: "{cm:LaunchProgram,CGDI}"; Flags: nowait postinstall skipifsilent

